apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vwr0nla3u-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vwr0nla3u-nodejs 
  name: vwr0nla3u-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vwr0nla3u-nodejs 
