apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vwr0nla3u-nodejs 
  janus-idp.io/tekton: vwr0nla3u-nodejs
  backstage.io/kubernetes-id: vwr0nla3u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vwr0nla3u-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml